#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2022,2023 Gene C
#
# installer script for dual-root 
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c (2023)
#
dest="$1"
self="dual-root"
dest=${dest%/}          # strip any trailing /

#
# info
#
info="README.rst Docs scripts packaging"
infodir="usr/share/${self}"

#
# license
#
license="Docs/License.rst"
licensedir="usr/share/licenses/${self}"

#
# systemd units
#
units='bind-mount-efi.service dual-root-syncd.service'
unitdir='usr/lib/systemd/system/'

#
# etc
#
conf='etc/sync-daemon.conf.sample'
etc1='etc/dual-root/*py'
etc2='etc/dual-root/lib/*py'
etcdir='etc/dual-root'

# apps
apps=('dual-root-tool')

# make app link in /usr/bin
# maybe move these to system site-directory

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # etc
    /usr/bin/rsync --mkpath -a ${etc1} ${dest}/${etcdir}/
    /usr/bin/rsync --mkpath -a ${etc2} ${dest}/${etcdir}/lib/
    /usr/bin/rsync --mkpath -a ${conf} ${dest}/${etcdir}/

    # shared
    /usr/bin/rsync --mkpath -a ${info} ${dest}/${infodir}/
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/
    /usr/bin/rsync --mkpath -a ${conf} ${dest}/${infodir}/

    # systemd units 
    /usr/bin/mkdir -p ${dest}/${unitdir}
    /usr/bin/rsync -a ${units} ${dest}/${unitdir}/

    # Executable
    if [ -v apps ] ; then
        /usr/bin/mkdir -p "${dest}/usr/bin"
        for app in ${apps[@]}
        do
            ln -sf /${etcdir}/${app}.py ${dest}/usr/bin/${app}
        done
    fi
    exit 0
fi

